# Generated by Django 6.0.5 on 2026-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
