# Generated by Django 6.0.5 on 2026-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
