# Generated by Django 6.0.5 on 2026-05-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='Product_Images',
        ),
    ]
