# Generated by Django 6.0.5 on 2026-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('negotiating', 'Negotiating'), ('pending_buyer_confirmation', 'Pending Buyer Confirmation'), ('awaiting_payment', 'Awaiting Payment'), ('sold_pending_release', 'Sold Pending Release'), ('booked', 'Booked'), ('pending_booking_confirmation', 'Pending Booking Confirmation'), ('dispute', 'Dispute'), ('completed', 'Completed'), ('expired', 'Expired')], default='available', max_length=40),
        ),
    ]
